b = [1 2 0 1];
a = [1 -0.5 0.25];
[delta,n] = impseq(0,0,100);
h = filter(b,a,delta);
Hf_1 = figure;
set(Hf_1,'NumberTitle','off','Name','P0219a');
Hs = stem(n,h,'filled');
set(Hs,'markersize',2);
axis([min(n)-5,max(n)+5,min(h)-0.5,max(h)+0.5]);
xlabel('n');
ylabel('h(n)');
title('Impulse response');